### ISSUE TITLE
Disconnect is not a function

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/bridge#191]
### Describe the problem you discovered

With Rabby (not frame for example), when we go to refund sheet after the selection of EVM wallet in the bridge sheet, an error occurs:

```
DartError: null : r.disconnect is not a function
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
errors.dart:296
packages/wagmi_flutter_web/src/wagmi_core.dart 560:7                         _guardFuture
wagmi_core.dart:560
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31           <fn>
async_patch.dart:60
dart-sdk/lib/async/zone.dart 1666:54                                         runBinary
zone.dart:1666
dart-sdk/lib/async/future_impl.dart 178:22                                   handleError
future_impl.dart:178
dart-sdk/lib/async/future_impl.dart 873:46                                   handleError
future_impl.dart:873
dart-sdk/lib/async/future_impl.dart 894:13                                   _propagateToListeners
future_impl.dart:894
dart-sdk/lib/async/future_impl.dart 674:5                                    [_completeError]
future_impl.dart:674
dart-sdk/lib/async/future_impl.dart 760:7                                    callback
future_impl.dart:760
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
schedule_microtask.dart:40
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
schedule_microtask.dart:49
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
```

**Comment by Chralu** [comment]
# Howto reproduce

1. go to bridge.testnet.archethic.net
2. delete browser data storage
3. select from bsc testnet -> connect to EVM wallet
4. reload page
5. WagmiCore config state keeps track of previous connection :

> window.wagmiCore.getConfig().state
> < ﻿{chainId: 97, connections: Map(2), current: '56fb22dbbdd', status: 'disconnected'}

6. Connect to EVM wallet. New connection created

> window.wagmiCore.getConfig().state
> < {chainId: 97, connections: Map(3), current: 'b2bd0575585', status: 'connected'}

we see that previous connections are still in the `connections` map.

7. select to archethic testnet => connect to aeWallet extension

8. Click on Disconnect button (top right of the bridge)

> window.wagmiCore.getConfig().state
> < {chainId: 97, connections: Map(2), current: '567e43cf7ed', status: 'connected'}

We see that wagmiCore falls back on an old, disabled, connection. And it acts as if connection was alive And Metamask says it is disconnected (which is true)

# Solution

Disable https://wagmi.sh/core/api/createConfig#storage.
That config parameter is not available in https://github.com/archethic-foundation/wagmi_flutter_web/ yet.

**Comment by Chralu** [comment]
Related to https://github.com/archethic-foundation/wagmi_flutter_web/issues/74
