### ISSUE TITLE
API to send funds if none are present on Archethic

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/bridge#3]
### Is your feature request related to a problem?

Sometimes users don't get UCO at first place but still want to participate in the ecosystem.
So we have to define some mechanism to support it.

### Describe the solution you'd like

We can define an API which can allocate dust UCO to users to pay the initial fees of the bridge.
This API should
- check if the Archethic's wallet doesn't have funds already
- check if the Ethereum's contract have been deployed and by this user.
- send dust UCO to pay the fees
- handle timeouts

### Additional context

The API  should support high concurrency of user requests

**Comment by redDwarf03** [comment]
https://github.com/archethic-foundation/bridge/pull/68
