### ISSUE TITLE
Bridge All UCO

### ISSUE THREAD

**Issue by ripcordChain** [archethic-foundation/bridge#49]
### Describe the problem you discovered

I had to bridge ~80K UCO from Mumbai Polygon Testnet to Archethic Testnet.

- 1st try: I selected "All" available UCO --> it failed after 1st EVM validation (publication of the contract)
         tx: https://mumbai.polygonscan.com/tx/0x7066f6cc398bd1f2622150eaad23d753f170637bc2c0aed1dd3317f59617d8ee
         Time out

- 2nd and 3rd try: same test, same result

- 4th try: I selected 1000 UCO --> Success
- 5th try: 5000 UCO --> Success
- 6th try: 10 000 UCO --> Success
- 7th try: 20 000 UCO --> Success
- 8th try: 30 000 UCO --> Success
- 9th try:  I selected "All" available UCO (only 1457,47 UCO remained) --> it failed after 1st EVM validation (publication of the contract)
         tx: https://mumbai.polygonscan.com/tx/0x469b1503d7489b1daa6345cc02ad0118c96dc326c06f43bba3de16d97e9d56f2
         Time out

Conclusion: it seems that it is not an issue related to the amout transferedbut the time out occured only when the "All" is selected to define the amout to transfer.

**Comment by ripcordChain** [comment]
Platform
Windows 10 64bits

Version of Archethic's wallet
2.3.3

Version of Archethic's Bridge
0.09 buil 11

EVM wallet
Metamask + Rabby

**Comment by redDwarf03** [comment]
Add a check to avoid having more than 8 decimals in the case of UCO, which does not accept more on the Archethic blockchain.
